[package]
name = "bevy_mod_imgui"
version = "0.9.0"
edition = "2021"
license = "MIT OR Apache-2.0"
categories = ["game-engines", "graphics", "gui", "rendering"]
description = "A Dear ImGui integration for the Bevy game engine."
readme = "README.md"
repository = "https://github.com/jbrd/bevy_mod_imgui"
rust-version = "1.92.0"
exclude = [".github/", ".gitignore"]

[features]
default = ["imgui-rs"]
imgui-rs = ["dep:imgui"]
docking = ["imgui-rs", "imgui/docking"]
dear-imgui-rs = ["dep:dear-imgui-rs", "dep:dear-imgui-wgpu"]

[dependencies]
imgui = { version = "0.12.0", optional = true }
wgpu = "27"

# For imgui_wgpu_rs_local
# imgui-wgpu = "0.24.0" # temporarily bundling imgui-wgpu with this crate
bytemuck = "1"
log = "0.4"
smallvec = "1"
dear-imgui-rs = { version = "0.9.0", optional = true, default-features = false }
dear-imgui-wgpu = { version = "0.9.0", optional = true, default-features = false, features = ["wgpu-27"] }

[dependencies.bevy]
version = "0.18.0"
default-features = false
features = ["bevy_core_pipeline", "bevy_render", "bevy_window"]

[dev-dependencies.bevy]
version = "0.18.0"
default-features = false
features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_render", "bevy_window", "bevy_winit", "png", "multi_threaded", "tonemapping_luts", "zstd_rust"]

[package.metadata.docs.rs]
all-features = false
features = ["imgui-rs", "docking"]

[[example]]
name = "custom-texture"
required-features = ["imgui-rs"]

[[example]]
name = "docking"
required-features = ["imgui-rs"]

[[example]]
name = "empty"
required-features = ["imgui-rs"]

[[example]]
name = "hello-world"
required-features = ["imgui-rs"]

[[example]]
name = "hello-world-postupdate"
required-features = ["imgui-rs"]

[[example]]
name = "minimal"
required-features = ["imgui-rs"]

[[example]]
name = "minimal-docking"
required-features = ["imgui-rs"]

[[example]]
name = "render-to-texture"
required-features = ["imgui-rs"]

[[example]]
name = "dear-minimal"
required-features = ["dear-imgui-rs"]
